name: Checks
on:
  check_suite:
    types: [completed]
  workflow_dispatch:
jobs:
  passed:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: echo "test"