name: Deploy CI
on:
  push:
    branches: [master]
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  vercel:
    name: Deploy to vercel
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - id: script
        uses: actions/github-script@v3
        with:
          script: |
            const isPr = [ 'pull_request', 'pull_request_target' ].includes(context.eventName)
            console.log(isPr)
            const ref = isPr ? context.payload.pull_request.head.ref : context.ref
            console.log(ref)
            const repo = isPr ? context.payload.pull_request.head.repo.full_name : context.repo.repo
            console.log(repo)
            return {ref, repo}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.script.outputs.result.ref }}
          repository: ${{ steps.script.outputs.result.repo }}

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@develop
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          ALIAS_DOMAINS: |
            {USER}-{REPO}-{BRANCH}.vercel.app
            gha-deploy.vercel.app
          PR_PREVIEW_DOMAIN: "{REPO}-{PR}.vercel.app"