name: Deploy CI
on:
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  vercel:
    name: Deploy to vercel
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.ref == 'refs/heads/master' }}
          if_true: '--prod'
          if_false: ''
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_PAT }}
          vercel-args: ${{ steps.condval.outputs.value }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 
          alias-domains: |
            gha-deploy.now.sh
