name: Deploy CI
on:
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  vercel:
    name: Deploy to vercel
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.ref == 'refs/heads/master' }}
          if_true: '--prod'
          if_false: ''

      - uses: altinukshini/deployment-action@releases/v1
        name: start deployment
        id: deployment
        with:
          token: ${{ secrets.GH_PAT}}
          description: "Deploying to Vercel"
          environment: production

      - uses: amondnet/vercel-action@v19
        name: Deploy to Vercel
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_PAT }}
          vercel-args: ${{ steps.condval.outputs.value }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 
          alias-domains: |
            gha-deploy.now.sh

      - name: update deployment status
        if: always()
        uses: altinukshini/deployment-status@releases/v1
        with:
          token: ${{ secrets.GH_PAT }}
          state: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          environment_url: ${{steps.vercel.outputs.preview-url}}
          description: "Successfully deployed to Vercel"
